export const LOAD_SCAN_DATA = 'LOAD_SCAN_DATA'
export const LOAD_CODE_DATA = 'LOAD_CODE_DATA'
export const LOAD_CAMPAIGN_DATA = 'LOAD_CAMPAIGN_DATA'
export const LOAD_PRODUCT_DATA = 'LOAD_PRODUCT_DATA'
export const LOAD_SMARTLABEL_DATA = 'LOAD_SMARTLABEL_DATA'
export const LOADING_DATA = 'LOADING_DATA'
export const DATA_LOADED = 'DATA_LOADED'

export const SET_USER_POSITION = 'SET_USER_POSITION'
export const LOAD_BLOCKCHAIN_CAMBIO_DATA = 'LOAD_BLOCKCHAIN_CAMBIO_DATA'

export const SAVE_URL_PARAMETERS = 'SAVE_URL_PARAMETERS'
