#
# DOCKER COMPOSE FILE FOR FULL-STACK COFFEECHAIN with BigchainDB
# - Uses the PYTHON API server to talk to BigchainDB
# - 1 Full BigchainDB node
# - Rest API exposed on 8000
#

version: '2'

services:

  coffeechain-api:
    build:
      context: ../server
      dockerfile: ./Dockerfile
    depends_on:
      - bigchaindb
    environment:
      BIGCHAINDB_ENABLED: 'True'
      BIGCHAINDB_API: 'http://bigchaindb:9984'
    ports:
      - "8000:8000"

  bigchaindb:
    depends_on:
      - mongodb
      - tendermint
    image: bigchaindb/bigchaindb:2.0.0-beta7
    environment:
      BIGCHAINDB_DATABASE_BACKEND: localmongodb
      BIGCHAINDB_DATABASE_HOST: mongodb
      BIGCHAINDB_DATABASE_PORT: 27017
      BIGCHAINDB_SERVER_BIND: 0.0.0.0:9984
      BIGCHAINDB_WSSERVER_HOST: 0.0.0.0
      BIGCHAINDB_WSSERVER_ADVERTISED_HOST: bigchaindb
      BIGCHAINDB_TENDERMINT_HOST: tendermint
      BIGCHAINDB_TENDERMINT_PORT: 26657
    ports:
      - "9984:9984"
      - "9985:9985"
      - "26658"
    command: start

  tendermint:
    image: tendermint/tendermint:0.22.8
    entrypoint: ''
    ports:
      - "26656:26656"
      - "26657:26657"
    command: sh -c "tendermint init && tendermint node --consensus.create_empty_blocks=false --proxy_app=tcp://bigchaindb:26658"

  mongodb:
    image: mongo:3.6
    ports:
      - "27017:27017"
    command: mongod
